language: node_js
node_js:
  - 0.10

env: BROWSERS=firefox E2E_BROWSERS=Firefox ENVIRONMENT=test

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver
  - npm run config

script:
  - npm run travis-unit
